language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - '7.1'
    - nightly
    - hhvm

matrix:
    fast_finish: true
    include:
        - php: '7.1'
          env:
              - 'COMPOSER_FLAGS=--prefer-lowest'
    allow_failures:
        - php: nightly
        - env: 'SYMFONY_VERSION=^3.3@dev'

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - if [ "$TRAVIS_PHP_VERSION" = "nightly" ]; then COMPOSER_FLAGS="$COMPOSER_FLAGS --ignore-platform-reqs"; fi;

install:
    - composer update $COMPOSER_FLAGS --no-interaction --prefer-dist --no-progress --no-suggest --ansi

script:
    - vendor/bin/phpunit
