build: false
platform: x86
clone_folder: c:\projects\dunglas\action-bundle

cache:
  - '%LOCALAPPDATA%\Composer\files'

init:
  - SET PATH=c:\tools\php;%PATH%

install:
  - cinst -y php --version 7.0.9 # Force the PHP version: http://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1
  - cd c:\tools\php
  - copy php.ini-production php.ini /Y
  - echo date.timezone="UTC" >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo memory_limit=1G >> php.ini
  - cd %APPVEYOR_BUILD_FOLDER%
  - php -r "readfile('http://getcomposer.org/installer');" | php
  - php composer.phar install --no-interaction --no-progress
  - appveyor DownloadFile https://phar.phpunit.de/phpunit.phar

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - php phpunit.phar --verbose
